package com.pojo;


public class Business {


    private User user;

    private Customer customer;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.id
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.cust_id
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.busi_type
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private Integer busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.busi_status
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private Integer busiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.busi_price
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private Double busiPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.busi_possibility
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private Integer busiPossibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.create_time
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.create_uid
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.busi_end_time
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private String busiEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.desc_info
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    private String descInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.id
     *
     * @return the value of tb_business.id
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.id
     *
     * @param id the value for tb_business.id
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.cust_id
     *
     * @return the value of tb_business.cust_id
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.cust_id
     *
     * @param custId the value for tb_business.cust_id
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.busi_type
     *
     * @return the value of tb_business.busi_type
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public Integer getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.busi_type
     *
     * @param busiType the value for tb_business.busi_type
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setBusiType(Integer busiType) {
        this.busiType = busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.busi_status
     *
     * @return the value of tb_business.busi_status
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public Integer getBusiStatus() {
        return busiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.busi_status
     *
     * @param busiStatus the value for tb_business.busi_status
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setBusiStatus(Integer busiStatus) {
        this.busiStatus = busiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.busi_price
     *
     * @return the value of tb_business.busi_price
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public Double getBusiPrice() {
        return busiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.busi_price
     *
     * @param busiPrice the value for tb_business.busi_price
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setBusiPrice(Double busiPrice) {
        this.busiPrice = busiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.busi_possibility
     *
     * @return the value of tb_business.busi_possibility
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public Integer getBusiPossibility() {
        return busiPossibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.busi_possibility
     *
     * @param busiPossibility the value for tb_business.busi_possibility
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setBusiPossibility(Integer busiPossibility) {
        this.busiPossibility = busiPossibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.create_time
     *
     * @return the value of tb_business.create_time
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.create_time
     *
     * @param createTime the value for tb_business.create_time
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.create_uid
     *
     * @return the value of tb_business.create_uid
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.create_uid
     *
     * @param createUid the value for tb_business.create_uid
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.busi_end_time
     *
     * @return the value of tb_business.busi_end_time
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public String getBusiEndTime() {
        return busiEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.busi_end_time
     *
     * @param busiEndTime the value for tb_business.busi_end_time
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setBusiEndTime(String busiEndTime) {
        this.busiEndTime = busiEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.desc_info
     *
     * @return the value of tb_business.desc_info
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.desc_info
     *
     * @param descInfo the value for tb_business.desc_info
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }
}