package com.pojo;


public class Concat {
    
    private User user;
    private Customer customer;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.cust_id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.concat_name
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String concatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.gender
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.job
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.telphone
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.wx_account
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String wxAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.borndate
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String borndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.address
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.photo
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.create_time
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.user_id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_concat.desc_info
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    private String descInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.id
     *
     * @return the value of tb_concat.id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.id
     *
     * @param id the value for tb_concat.id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.cust_id
     *
     * @return the value of tb_concat.cust_id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.cust_id
     *
     * @param custId the value for tb_concat.cust_id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.concat_name
     *
     * @return the value of tb_concat.concat_name
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getConcatName() {
        return concatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.concat_name
     *
     * @param concatName the value for tb_concat.concat_name
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setConcatName(String concatName) {
        this.concatName = concatName == null ? null : concatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.gender
     *
     * @return the value of tb_concat.gender
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.gender
     *
     * @param gender the value for tb_concat.gender
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.job
     *
     * @return the value of tb_concat.job
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.job
     *
     * @param job the value for tb_concat.job
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.telphone
     *
     * @return the value of tb_concat.telphone
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.telphone
     *
     * @param telphone the value for tb_concat.telphone
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.wx_account
     *
     * @return the value of tb_concat.wx_account
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getWxAccount() {
        return wxAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.wx_account
     *
     * @param wxAccount the value for tb_concat.wx_account
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setWxAccount(String wxAccount) {
        this.wxAccount = wxAccount == null ? null : wxAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.borndate
     *
     * @return the value of tb_concat.borndate
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getBorndate() {
        return borndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.borndate
     *
     * @param borndate the value for tb_concat.borndate
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setBorndate(String borndate) {
        this.borndate = borndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.address
     *
     * @return the value of tb_concat.address
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.address
     *
     * @param address the value for tb_concat.address
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.photo
     *
     * @return the value of tb_concat.photo
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.photo
     *
     * @param photo the value for tb_concat.photo
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.create_time
     *
     * @return the value of tb_concat.create_time
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.create_time
     *
     * @param createTime the value for tb_concat.create_time
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.user_id
     *
     * @return the value of tb_concat.user_id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.user_id
     *
     * @param createId the value for tb_concat.user_id
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_concat.desc_info
     *
     * @return the value of tb_concat.desc_info
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_concat.desc_info
     *
     * @param descInfo the value for tb_concat.desc_info
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }
}