package com.pojo;

public class Customer {

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.id
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.user_id
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.cust_name
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.cust_type
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private Integer custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.telphone
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.net_address
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private String netAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.address
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.cust_status
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private Integer custStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.create_time
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.create_uid
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.desc_info
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    private String descInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.id
     *
     * @return the value of tb_customer.id
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.id
     *
     * @param id the value for tb_customer.id
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.user_id
     *
     * @return the value of tb_customer.user_id
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.user_id
     *
     * @param userId the value for tb_customer.user_id
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.cust_name
     *
     * @return the value of tb_customer.cust_name
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.cust_name
     *
     * @param custName the value for tb_customer.cust_name
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.cust_type
     *
     * @return the value of tb_customer.cust_type
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public Integer getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.cust_type
     *
     * @param custType the value for tb_customer.cust_type
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setCustType(Integer custType) {
        this.custType = custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.telphone
     *
     * @return the value of tb_customer.telphone
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.telphone
     *
     * @param telphone the value for tb_customer.telphone
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.net_address
     *
     * @return the value of tb_customer.net_address
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public String getNetAddress() {
        return netAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.net_address
     *
     * @param netAddress the value for tb_customer.net_address
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setNetAddress(String netAddress) {
        this.netAddress = netAddress == null ? null : netAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.address
     *
     * @return the value of tb_customer.address
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.address
     *
     * @param address the value for tb_customer.address
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.cust_status
     *
     * @return the value of tb_customer.cust_status
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public Integer getCustStatus() {
        return custStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.cust_status
     *
     * @param custStatus the value for tb_customer.cust_status
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setCustStatus(Integer custStatus) {
        this.custStatus = custStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.create_time
     *
     * @return the value of tb_customer.create_time
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.create_time
     *
     * @param createTime the value for tb_customer.create_time
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.create_uid
     *
     * @return the value of tb_customer.create_uid
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.create_uid
     *
     * @param createUid the value for tb_customer.create_uid
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.desc_info
     *
     * @return the value of tb_customer.desc_info
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.desc_info
     *
     * @param descInfo the value for tb_customer.desc_info
     *
     * @mbggenerated Mon Nov 28 15:36:29 CST 2022
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }
}