package com.pojo;

public class Goods {

    private Provider provider;
    private User user;

    public Provider getProvider() {
        return provider;
    }

    public void setProvider(Provider provider) {
        this.provider = provider;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.id
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.provider_id
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private Long providerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_name
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.unit
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.cost
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private Double cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.sale_price
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private Double salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.create_time
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.create_uid
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.desc_info
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private String descInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_img
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    private String goodsImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.id
     *
     * @return the value of tb_goods.id
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.id
     *
     * @param id the value for tb_goods.id
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.provider_id
     *
     * @return the value of tb_goods.provider_id
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.provider_id
     *
     * @param providerId the value for tb_goods.provider_id
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_name
     *
     * @return the value of tb_goods.goods_name
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_name
     *
     * @param goodsName the value for tb_goods.goods_name
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.unit
     *
     * @return the value of tb_goods.unit
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.unit
     *
     * @param unit the value for tb_goods.unit
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.cost
     *
     * @return the value of tb_goods.cost
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.cost
     *
     * @param cost the value for tb_goods.cost
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.sale_price
     *
     * @return the value of tb_goods.sale_price
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public Double getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.sale_price
     *
     * @param salePrice the value for tb_goods.sale_price
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.create_time
     *
     * @return the value of tb_goods.create_time
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.create_time
     *
     * @param createTime the value for tb_goods.create_time
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.create_uid
     *
     * @return the value of tb_goods.create_uid
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.create_uid
     *
     * @param createUid the value for tb_goods.create_uid
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.desc_info
     *
     * @return the value of tb_goods.desc_info
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.desc_info
     *
     * @param descInfo the value for tb_goods.desc_info
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_img
     *
     * @return the value of tb_goods.goods_img
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_img
     *
     * @param goodsImg the value for tb_goods.goods_img
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }
}