package com.dao;

import com.pojo.Business;
import java.util.List;
import java.util.Map;

public interface BusinessMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business
     *
     * @mbggenerated Thu Dec 01 14:06:44 CST 2022
     */
    int insertSelective(Business record);

    /**
     * 查询商机记录表
     * @param map
     * @return
     */
    List<Business> selectBusinessByPage(Map<String,Object> map);

    /**
     * 商机总数
     * @param map
     * @return
     */
    int selectCountOfCustomer(Map<String,Object> map);

    /**
     * 添加商机信息
     * @param business
     * @return
     */
    int insertBusiness(Business business);

    /**
     * 根据id删除商机信息表
     * @param ids
     * @return
     */
    int deleteBusinessByIds(long[] ids);

    /**
     * 根据id查询商机信息
     * @param id
     * @return
     */
    Business selectBusinessById(long id);

    /**
     * 保存修改的商机信息
     * @param business
     * @return
     */
    int updateBusiness(Business business);

}