package com.dao;

import com.pojo.Chats;

import java.util.List;
import java.util.Map;

public interface ChatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chats
     *
     * @mbggenerated Mon Nov 28 15:55:36 CST 2022
     */
    int insert(Chats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chats
     *
     * @mbggenerated Mon Nov 28 15:55:36 CST 2022
     */
    int insertSelective(Chats record);

    /**
     * 查询客户聊天记录
     * @param map
     * @return
     */
    List<Chats> selectChatsByPage(Map<String,Object> map);

    /**
     * 聊天记录总数
     * @param map
     * @return
     */
    int selectCountOfChats(Map<String,Object> map);

    /**
     * 添加新聊天记录
     * @param chats
     * @return
     */
    int insertChats(Chats chats);

    /**
     * 删除聊天记录
     * @param ids
     * @return
     */
    int deleteChatsByIds(String[] ids);

    /**
     * 根据id查询聊天记录
     * @param id
     * @return
     */
    Chats selectChatsById(long id);

    /**
     * 保存修改聊天记录信息
     * @param chats
     * @return
     */
    int updateChats(Chats chats);

}