package com.dao;

import com.pojo.Concat;

import java.util.List;
import java.util.Map;

public interface ConcatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_concat
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    int insert(Concat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_concat
     *
     * @mbggenerated Tue Nov 29 15:57:07 CST 2022
     */
    int insertSelective(Concat record);

    /**
     * 查询联系人列表
     * @param map
     * @return
     */
    List<Concat> selectConcatByPage(Map<String,Object> map);

    /**
     * 查询联系人总数
     * @param map
     * @return
     */
    int selectCountOfConcat(Map<String,Object> map);

    /**
     * 添加新联系人
     * @param concat
     * @return
     */
    int insertConcat(Concat concat);

    /**
     * 根据id值删除联系人
     * @param ids
     * @return
     */
    int deleteConcatByIds(String[] ids);

    /**
     * 根据id查询联系人
     * @param id
     * @return
     */
    Concat selectConcatById(long id);

    /**
     * 保存修改联系人信息
     * @param concat
     * @return
     */
    int updateConcat(Concat concat);

}