package com.dao;

import com.pojo.Goods;

import java.util.List;
import java.util.Map;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated Thu Dec 01 13:44:06 CST 2022
     */
    int insertSelective(Goods record);

    /**
     * 查询客户信息
     * @param map
     * @return
     */
    List<Goods> selectGoodsByPage(Map<String,Object> map);

    /**
     * 查询总数
     * @param map
     * @return
     */
    int selectCountOfGoods(Map<String,Object> map);

    /**
     * 添加新商品
     * @param goods
     * @return
     */
    int insertGoods(Goods goods);

    /**
     * 删除商品
     * @param ids
     * @return
     */
    int deleteGoodsByIds(long[] ids);

    /**
     * 根据id查询商品信息
     * @param id
     * @return
     */
    Goods selectGoodsById(long id);

    /**
     * 保存修改的商品
     * @param goods
     * @return
     */
    int updateGoods(Goods goods);


    List<Goods> selectAllGoods();

}