package com.dao;

import com.pojo.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Nov 29 16:03:52 CST 2022
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Nov 29 16:03:52 CST 2022
     */
    int insertSelective(Role record);
}